"""create setting

Revision ID: 1c0beef7c9a6
Revises: d4c0ecd18270
Create Date: 2026-04-05 20:21:15.711736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0beef7c9a6'
down_revision: Union[str, Sequence[str], None] = 'd4c0ecd18270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_setting',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_user_setting_user_key')
    )
    op.create_index(op.f('ix_user_setting_id'), 'user_setting', ['id'], unique=False)
    op.create_index(op.f('ix_user_setting_user_id'), 'user_setting', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_setting_user_id'), table_name='user_setting')
    op.drop_index(op.f('ix_user_setting_id'), table_name='user_setting')
    op.drop_table('user_setting')
    # ### end Alembic commands ###
